name: My first pipeline
on:
  push:
    branches: main
jobs:
  hello:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: hello world
         run: echo "hello world welcome to my life"
         shell: bash
         
       
    
